### DISCUSSION TITLE
Centre logo in mobile view

### DISCUSSION THREAD

**Discussion by fvlasie** [breezefront/community#126] [1. Help] [answered]
Hello!

Is it possible to centre the logo in the header content area in the mobile view?

Thank you!

**Comment by vovayatsyuk** [comment]
It's hard to give a good answer without knowing your header contents. A link to the site would be perfect.

**Reply by fvlasie** [reply]
Thank you for your help.

When the screen width is around 600px there is a large white space to the right of the logo.

**Reply by vovayatsyuk** [reply, marked as answer]
I'd go with this simplest solution:

```less
& when (@critical) {
    .nav-toggle {
        position: absolute;
    }
    @media @media-sm-down {
        .logo {
            margin: 0 auto;
        }
    }
}
```
