### DISCUSSION TITLE
Sticky header

### DISCUSSION THREAD

**Discussion by dheerajKsharma** [breezefront/community#139] [1. Help] [answered]
Hi,
Is their any option to enable Sticky Header in breeze blank theme?

**Comment by vovayatsyuk** [comment, marked as answer]
You can do this with a custom css file:

```css
.navigation-wrapper {
    position: sticky;
    top: 0;
    left: 0;
    z-index: 50;
    background: #fff;
}
```

If you want to stick the whole header with navigation, you need to [move navigation inside the header](https://breezefront.com/docs/menu#layout-update), and then add similar styles, but for the `.page-header` selector.
