### DISCUSSION TITLE
Inconsistent LESS compilation behavior between Grunt and server-side compilation

### DISCUSSION THREAD

**Discussion by webbedfeet-stu** [breezefront/community#252] [1. Help]
I started running into an issue when trying to apply variable overwrites in a child theme to the block classes, such as `@block-title__font-size`.

The issue I was having was when using the frontend tool stack of Grunt, these changes were not coming through to the compiled CSS. However, when using the server-side LESS compilation to generate the CSS on-the-fly, these changes were coming in.

After a long debug, I found that the version of `less.js`, used by `grunt-contrib-less` in the latest version of Magento (`2.4.6-p4` and possibly older versions) is much newer than the `less.js` version used by Magento through PHP:

|  | `wikimedia/less.php` | `grunt-contrib-less` |
|---|---|---|
| `less.js` version | `2.5.3` | `3.0.4` | 

The problematic line when using the Grunt compilation for me was in `vendor/swissup/theme-frontend-breeze-blank/web/css/default.less:6` of:

`@import (reference) 'abstracts/_all.less';`

If I removed the `(reference)` declaration it would work.

Looking through less.js changelogs, in `2.6.0` they made a change to how reference imports worked https://github.com/less/less.js/pull/2729 which I think is why the import doesn't work correctly when using the later version of `less.js` through Grunt.

I thought I'd raise this here as I'm not sure if this is something that you are already aware of, but I'm sure things like this can happen especially as the version of `less.js` Magento 2 still use through PHP is almost 10 years old.

Thanks

**Comment by vovayatsyuk** [comment]
Thank you for such a detailed description!

It seems that the newest less.js doesn't support nested extends from referenced less imports:

```less
// 1. Contents of "@import (reference) a.less":
.abstract-block {
    font-size: 16px;
    .title {
        &:extend(.abstract-block-title all);
    }
}
.abstract-block-title {
    font-size: 20px;
}

// 2. Contents of "@import b.less"
.block {
    &:extend(.abstract-block all);
}

// 3. Output
.block {
    font-size: 16px;
}
```

Here is an output without  `@import (reference)` usage:

```less
.abstract-block,
.block {
    font-size: 16px;
}
.abstract-block-title,
.block .title {
    font-size: 20px;
}
```

The easiest solution would be removing the `(reference)` usage, but it will increase the CSS file size a bit.
