### DISCUSSION TITLE
Pagebuilder breaking points not working

### DISCUSSION THREAD

**Discussion by midhung123** [breezefront/community#315] [5. General]
Hi, I have created a product slider using the page builder on my home page and added breakpoints using view.xml in my breeze theme but it is not working. For the mobile view, we only need to show 1 or 1.5 products per slider it is working when I switch to the default Magento theme but it is not working with Breeze any solution for this?

**Comment by vovayatsyuk** [comment]
Hello, you can use css:

```css
& when (@critical) {
    @media @media-md-down {
        [data-appearance="carousel"] {
            --listing-grid-columns: 1.5;
        }
    }
}
```
